version: '3'

services:
  entrainement:
    image: alexluneau/mlflow
    networks:
      - rakuten_network
     

    volumes:
      - ../rclone/data/MLflow:/app/MLflow
      #- /mnt/d/MLops_Rakuten/data:/app/data ##Pour essayer sur les images stock√©es en local
    ports:
      - 5000:5000

volumes:
  rakuten_volume:

networks:
  rakuten_network:
     driver : bridge
