version: '3'

services:
  mlflow-server:
    image: alexluneau/mlflow
    networks:
      - rakuten_network
     

    volumes:
      - ../rclone/data/MLflow:/app/
    
     
    ports:
      - 5000:5000
    
    environment:
      - MLFLOW_TRACKING_URI=/app/
      - MLFLOW_ARTIFACT_URI=/app/


networks:
  rakuten_network:
     #driver : bridge
     external: true
